//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressStat
    {
        public long StatsId { get; set; }
        public string Address { get; set; }
        public Nullable<int> AddressIndex { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> Account_Id { get; set; }
        public Nullable<bool> SendToAdmin { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<long> Payment_Id { get; set; }
        public Nullable<decimal> MiningFee { get; set; }
        public Nullable<bool> GasSent { get; set; }
        public string GasTransHash { get; set; }
        public string TransferTransHash { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
