//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandlesData
    {
        public long Id { get; set; }
        public string SymbolName { get; set; }
        public Nullable<decimal> H { get; set; }
        public Nullable<decimal> L { get; set; }
        public Nullable<decimal> O { get; set; }
        public Nullable<decimal> C { get; set; }
        public Nullable<long> TimeStamp { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string TimeFrame { get; set; }
        public string TimeFrameOriginal { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
