//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Currency()
        {
            this.Pairs = new HashSet<Pair>();
            this.Pairs1 = new HashSet<Pair>();
        }
    
        public int CurrencyId { get; set; }
        public string FullName { get; set; }
        public string ThreeDigitName { get; set; }
        public Nullable<bool> IsFiat { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Confirms { get; set; }
        public Nullable<bool> CanConvert { get; set; }
        public string ImgURL { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<bool> IsToken { get; set; }
        public Nullable<decimal> BuySpread { get; set; }
        public Nullable<decimal> SellSpread { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pair> Pairs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pair> Pairs1 { get; set; }
    }
}
