//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionAccess
    {
        public long FunctionAccessId { get; set; }
        public Nullable<byte> UserRoleTypeId { get; set; }
        public Nullable<int> FunctionRequestId { get; set; }
        public Nullable<bool> IsAccessible { get; set; }
    
        public virtual FunctionRequest FunctionRequest { get; set; }
        public virtual UserRoleType UserRoleType { get; set; }
    }
}
