//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYC
    {
        public long Id { get; set; }
        public long AccId { get; set; }
        public string FirstDocument { get; set; }
        public string SecondDocument { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
