//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaunchPadApplicationQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaunchPadApplicationQuestion()
        {
            this.LaunchPadApplicationAnswers = new HashSet<LaunchPadApplicationAnswer>();
        }
    
        public long Id { get; set; }
        public string Question { get; set; }
        public string CheckBox { get; set; }
        public string RadioButton { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsHaveOther { get; set; }
        public Nullable<long> LaunchPadQuestionType_id { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaunchPadApplicationAnswer> LaunchPadApplicationAnswers { get; set; }
        public virtual LaunchPadApplicationQuestionType LaunchPadApplicationQuestionType { get; set; }
    }
}
