//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaunchPadApplicationAnswer
    {
        public long Id { get; set; }
        public Nullable<long> LaunchPadApplication_Id { get; set; }
        public Nullable<long> LaunchPadApplicationQuestion_Id { get; set; }
        public string PlainText { get; set; }
        public string FileUrl { get; set; }
        public string CheckBox { get; set; }
        public string RadioButton { get; set; }
        public string Other { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual LaunchPadApplication LaunchPadApplication { get; set; }
        public virtual LaunchPadApplicationQuestion LaunchPadApplicationQuestion { get; set; }
    }
}
