//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaunchPadCurrency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaunchPadCurrency()
        {
            this.LaunchPadPayments = new HashSet<LaunchPadPayment>();
            this.LaunchPadWallets = new HashSet<LaunchPadWallet>();
        }
    
        public long Id { get; set; }
        public string CurrecnyFullName { get; set; }
        public string CurrencyShortName { get; set; }
        public string SmartContractAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> LaunchPadCurrencyStatus_Id { get; set; }
        public string CurrencyIconUrl { get; set; }
        public string OfficialWebSiteUrl { get; set; }
        public string WhitePaperUrl { get; set; }
        public Nullable<System.DateTime> SaleStartDateTime { get; set; }
        public Nullable<System.DateTime> SaleEndDateTime { get; set; }
        public Nullable<decimal> TotalSupply { get; set; }
        public Nullable<decimal> RemaingSupply { get; set; }
        public Nullable<long> LaunchPadApplication_Id { get; set; }
        public string SupplyDepositAddress { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<bool> IsOnSale { get; set; }
    
        public virtual LaunchPadApplication LaunchPadApplication { get; set; }
        public virtual LaunchPadCurrencyStatu LaunchPadCurrencyStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaunchPadPayment> LaunchPadPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaunchPadWallet> LaunchPadWallets { get; set; }
    }
}
