//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaunchPadApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaunchPadApplication()
        {
            this.LaunchPadApplicationAnswers = new HashSet<LaunchPadApplicationAnswer>();
            this.LaunchPadCurrencies = new HashSet<LaunchPadCurrency>();
        }
    
        public long Id { get; set; }
        public Nullable<long> LaunchPadApplicationStatus_Id { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<System.DateTime> CanceledDateTime { get; set; }
        public string CanceledReason { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> ReviewDateTime { get; set; }
        public Nullable<System.DateTime> AcceptDateTime { get; set; }
    
        public virtual LaunchPadCurrencyStatu LaunchPadCurrencyStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaunchPadApplicationAnswer> LaunchPadApplicationAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaunchPadCurrency> LaunchPadCurrencies { get; set; }
    }
}
