//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pair
    {
        public long PairId { get; set; }
        public string BaseCurrency { get; set; }
        public string MarketCurrency { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> PairedDate { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> BaseCurrencyId { get; set; }
        public Nullable<int> MarketCurrencyId { get; set; }
        public string MarketSymbol { get; set; }
        public Nullable<double> Bid { get; set; }
        public Nullable<double> Ask { get; set; }
        public Nullable<double> Last { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> Change { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
    }
}
