//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefferalCode
    {
        public long RefferalCodeId { get; set; }
        public Nullable<long> Account_Id { get; set; }
        public string RefferalCodeName { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> RefferalCodeIndex { get; set; }
        public Nullable<long> RefferalCodeStatus_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual RefferalCodeStatu RefferalCodeStatu { get; set; }
    }
}
