//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public long TradeId { get; set; }
        public string TradeType { get; set; }
        public System.DateTime TradeDate { get; set; }
        public string Currency { get; set; }
        public string Symbol { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Status { get; set; }
        public Nullable<double> Fee { get; set; }
        public Nullable<long> Account_Id { get; set; }
        public Nullable<long> Wallet_Id { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> PnL { get; set; }
        public string Direction { get; set; }
        public long TradeTypeValue { get; set; }
        public Nullable<long> expiryTime { get; set; }
        public Nullable<decimal> ExitPrice { get; set; }
        public Nullable<bool> IsOneClickOrder { get; set; }
        public Nullable<bool> StopLoss_TakeProfitEn { get; set; }
        public Nullable<decimal> UpLimitValue { get; set; }
        public Nullable<decimal> DownLimitValue { get; set; }
        public Nullable<System.DateTime> TradeClose_Date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Wallet Wallet { get; set; }
    }
}
