//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wallet()
        {
            this.Trades = new HashSet<Trade>();
        }
    
        public long WalletId { get; set; }
        public string Currency { get; set; }
        public string WalletAddress { get; set; }
        public Nullable<int> AddressIndex { get; set; }
        public string BarcodeImageURL { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string WalletType { get; set; }
        public string DesTag { get; set; }
        public string PublicKey { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> BalanceStoshis { get; set; }
        public Nullable<long> Account_Id { get; set; }
        public Nullable<bool> UnderProcessed { get; set; }
        public Nullable<bool> LowBalance { get; set; }
        public string AddressTag { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trade> Trades { get; set; }
    }
}
